# Generated by Django 5.0.1 on 2024-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('max_amount_of_members', models.IntegerField()),
                ('private', models.BooleanField()),
                ('owner', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('custom', 'Пользовательская'), ('lesson', 'Урок')], max_length=6, verbose_name='Статус')),
            ],
        ),
    ]
